"""Initial schema with all models

Revision ID: 6c2ec0cc1b58
Revises:
Create Date: 2025-12-23 12:29:13.594592

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c2ec0cc1b58"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "calc_comparison",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "calc_comparison",
        "flowsheet_version_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "calc_run", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.alter_column(
        "calc_run",
        "flowsheet_version_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "calc_run",
        "scenario_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "calc_run",
        "started_by_user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.add_column("calc_scenario", sa.Column("project_id", sa.Integer(), nullable=False))
    op.add_column(
        "calc_scenario",
        sa.Column("is_recommended", sa.Boolean(), server_default="0", nullable=False),
    )
    op.add_column("calc_scenario", sa.Column("recommendation_note", sa.Text(), nullable=True))
    op.add_column(
        "calc_scenario", sa.Column("recommended_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "calc_scenario", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.alter_column(
        "calc_scenario",
        "flowsheet_version_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "calc_scenario",
        "created_by_user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "calc_scenario", "project", ["project_id"], ["id"])
    op.add_column("comment", sa.Column("project_id", sa.Integer(), nullable=False))
    op.add_column("comment", sa.Column("scenario_id", sa.UUID(), nullable=True))
    op.add_column("comment", sa.Column("calc_run_id", sa.UUID(), nullable=True))
    op.alter_column(
        "comment", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.create_foreign_key(None, "comment", "calc_scenario", ["scenario_id"], ["id"])
    op.create_foreign_key(None, "comment", "project", ["project_id"], ["id"])
    op.create_foreign_key(None, "comment", "calc_run", ["calc_run_id"], ["id"])
    op.drop_column("comment", "entity_type")
    op.drop_column("comment", "entity_id")
    op.drop_column("comment", "updated_at")
    op.alter_column(
        "flowsheet", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.alter_column(
        "flowsheet",
        "plant_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "flowsheet",
        "created_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "flowsheet",
        "updated_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "flowsheet_version",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "flowsheet_version",
        "flowsheet_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "flowsheet_version",
        "created_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "plant", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.alter_column(
        "project", "plant_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=True
    )
    op.alter_column(
        "project_flowsheet_version",
        "flowsheet_version_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "unit", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.alter_column(
        "unit",
        "flowsheet_version_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "unit",
        "equipment_type_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "unit",
        "equipment_type_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "unit",
        "flowsheet_version_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "unit", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.alter_column(
        "project_flowsheet_version",
        "flowsheet_version_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "project", "plant_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=True
    )
    op.alter_column(
        "plant", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.alter_column(
        "flowsheet_version",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "flowsheet_version",
        "flowsheet_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "flowsheet_version",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "flowsheet",
        "updated_by",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "flowsheet",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "flowsheet",
        "plant_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "flowsheet", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.add_column(
        "comment",
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column("comment", sa.Column("entity_id", sa.NUMERIC(), nullable=False))
    op.add_column("comment", sa.Column("entity_type", sa.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.alter_column(
        "comment", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.drop_column("comment", "calc_run_id")
    op.drop_column("comment", "scenario_id")
    op.drop_column("comment", "project_id")
    op.drop_constraint(None, "calc_scenario", type_="foreignkey")
    op.alter_column(
        "calc_scenario",
        "created_by_user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "calc_scenario",
        "flowsheet_version_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "calc_scenario", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.drop_column("calc_scenario", "recommended_at")
    op.drop_column("calc_scenario", "recommendation_note")
    op.drop_column("calc_scenario", "is_recommended")
    op.drop_column("calc_scenario", "project_id")
    op.alter_column(
        "calc_run",
        "started_by_user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "calc_run",
        "scenario_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "calc_run",
        "flowsheet_version_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "calc_run", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.alter_column(
        "calc_comparison",
        "flowsheet_version_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "calc_comparison",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
